// This file is automatically generated
// tslint:disabled

import Icon from './base/baseIcon'
import FaBr500px from './icons/FaBr500px'

const IconObj: any = Icon
IconObj.FaBr500px = FaBr500px

export default IconObj
