const generate = require('@xl-vision/icon-generator').default
const path = require('path')
const fs = require('fs-extra')
const toCamel = require('./toCamel')
const config = require('./config')

const iconDestPath = path.join(__dirname, '../../src/icon/icons')
const iconIndexPath = path.join(iconDestPath, '../index.ts')

const run = async () => {
  await fs.remove(iconDestPath)
  await fs.remove(iconIndexPath)

  await generate(config)

  let importContent = "import createIcon from './base/createIcon'\n"
  let exportContent = '{\n  createIcon'
  // 获取icons目录下所有的icon，生成index.ts文件
  const files = await fs.readdir(iconDestPath)

  files.forEach((it) => {
    const name = it.substring(0, it.length - path.extname(it).length)
    importContent += `import ${toCamel(name)} from './icons/${name}'\n`
    exportContent += `,\n  ${toCamel(name)}`
  })
  exportContent += '\n}\n'
  let allContent = '// This file is automatically generated\n/* eslint-disable */\n\n'
  allContent += importContent

  allContent += "export { BaseIconProps } from './base/base-icon'\n"
  allContent += "export { IconProps } from './base/createIcon'\n"
  allContent += `export default ${exportContent}\n`
  allContent += `export ${exportContent}\n`

  fs.writeFileSync(iconIndexPath, allContent)
}

run()
