/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M445.2 48.05L398 48H128c-54.3 0-64 35.7-64 48 30.3 4.2 48 8 48 40v264a64 64 0 0064 64h192a64 64 0 0064-64V96c0-19 11.5-38.35 12.6-40 1.2-1.9 3.4-4.4 3.4-5.5s-.3-2.45-2.8-2.45z'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M112 176L432 176'/>
    </svg>
)

const BeakerOutline = createIcon(svgElement)

BeakerOutline.displayName = 'BeakerOutline'

export { IconProps } from './base/createIcon'

export default BeakerOutline
