/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <circle cx='256' cy='56' r='56'/><path d='M464 128L48 128 48 180 192 180 160 505.13 211 512 232.65 320 279.67 320 301 512 352 505.02 320 180 464 180 464 128z'/>
    </svg>
)

const BodySharp = createIcon(svgElement)

BodySharp.displayName = 'BodySharp'

export { IconProps } from './base/createIcon'

export default BodySharp
