/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <circle cx='176' cy='416' r='32'/><circle cx='400' cy='416' r='32'/><path d='M167.78 304L429.12 304 467.52 112 133.89 112 125.42 64 32 64 32 96 98.58 96 146.58 368 432 368 432 336 173.42 336 167.78 304z'/>
    </svg>
)

const CartSharp = createIcon(svgElement)

CartSharp.displayName = 'CartSharp'

export { IconProps } from './base/createIcon'

export default CartSharp
