/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='48' d='M184 112L328 256 184 400'/>
    </svg>
)

const ChevronForwardSharp = createIcon(svgElement)

ChevronForwardSharp.displayName = 'ChevronForwardSharp'

export { IconProps } from './base/createIcon'

export default ChevronForwardSharp
