/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='48' d='M112 184L256 328 400 184'/>
    </svg>
)

const ChevronDown = createIcon(svgElement)

ChevronDown.displayName = 'ChevronDown'

export { IconProps } from './base/createIcon'

export default ChevronDown
