/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='42' d='M160 368L32 256 160 144'/><path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='42' d='M352 368L480 256 352 144'/><path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='42' d='M192 288.1L256 352 320 288.1'/><path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='42' d='M256 160L256 336.03'/>
    </svg>
)

const CodeDownloadSharp = createIcon(svgElement)

CodeDownloadSharp.displayName = 'CodeDownloadSharp'

export { IconProps } from './base/createIcon'

export default CodeDownloadSharp
