/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <circle cx='128' cy='416' r='48' fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M128 144L128 368'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M288 160L224 96 288 32'/><circle cx='128' cy='96' r='48' fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32'/><circle cx='384' cy='416' r='48' fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M240 96h84a60 60 0 0160 60v212'/>
    </svg>
)

const GitPullRequestOutline = createIcon(svgElement)

GitPullRequestOutline.displayName = 'GitPullRequestOutline'

export { IconProps } from './base/createIcon'

export default GitPullRequestOutline
