/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <rect width='352' height='352' x='80' y='80' fill='none' strokeLinejoin='round' strokeWidth='32' rx='48' ry='48'/><rect width='224' height='224' x='144' y='144' fill='none' strokeLinejoin='round' strokeWidth='32' rx='16' ry='16'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M256 80L256 48'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M336 80L336 48'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M176 80L176 48'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M256 464L256 432'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M336 464L336 432'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M176 464L176 432'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M432 256L464 256'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M432 336L464 336'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M432 176L464 176'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M48 256L80 256'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M48 336L80 336'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M48 176L80 176'/>
    </svg>
)

const HardwareChipOutline = createIcon(svgElement)

HardwareChipOutline.displayName = 'HardwareChipOutline'

export { IconProps } from './base/createIcon'

export default HardwareChipOutline
