/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M192 448L320 448'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M384 208v32c0 70.4-57.6 128-128 128h0c-70.4 0-128-57.6-128-128v-32'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M256 368L256 448'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M256 64a63.68 63.68 0 00-64 64v111c0 35.2 29 65 64 65s64-29 64-65V128c0-36-28-64-64-64z'/>
    </svg>
)

const MicOutline = createIcon(svgElement)

MicOutline.displayName = 'MicOutline'

export { IconProps } from './base/createIcon'

export default MicOutline
