/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M256 48A208.23 208.23 0 0048 256c0 114.68 93.31 208 208 208a208.23 208.23 0 00208-208c0-114.69-93.31-208-208-208zm-8 361V264H103l259-114.11z'/>
    </svg>
)

const NavigateCircleSharp = createIcon(svgElement)

NavigateCircleSharp.displayName = 'NavigateCircleSharp'

export { IconProps } from './base/createIcon'

export default NavigateCircleSharp
