/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M96 304L416 304'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M96 208L416 208'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M96 112L416 112'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M96 400L416 400'/>
    </svg>
)

const ReorderFourOutline = createIcon(svgElement)

ReorderFourOutline.displayName = 'ReorderFourOutline'

export { IconProps } from './base/createIcon'

export default ReorderFourOutline
