/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M256 32L256 480'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M313.72 80A111.47 111.47 0 01256 96a111.47 111.47 0 01-57.72-16M198.28 432a112.11 112.11 0 01115.44 0'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M449.99 144L62.01 368'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M437.27 218a112.09 112.09 0 01-57.71-100M74.73 294a112.09 112.09 0 0157.71 100'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M62.01 144L449.99 368'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M74.73 218a112.09 112.09 0 0057.71-100M437.27 294a112.09 112.09 0 00-57.71 100'/>
    </svg>
)

const SnowOutline = createIcon(svgElement)

SnowOutline.displayName = 'SnowOutline'

export { IconProps } from './base/createIcon'

export default SnowOutline
