/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M430 0H82a18 18 0 00-18 18v476a18 18 0 0018 18h348a18 18 0 0018-18V18a18 18 0 00-18-18zM100 448V64h312v384z'/>
    </svg>
)

const TabletPortraitSharp = createIcon(svgElement)

TabletPortraitSharp.displayName = 'TabletPortraitSharp'

export { IconProps } from './base/createIcon'

export default TabletPortraitSharp
