/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M157.65 176.1L64 176.1 64 335.9 157.65 335.9 288 440 288 72 157.65 176.1z'/><path fill='none' strokeLinecap='square' strokeLinejoin='round' strokeWidth='32' d='M352 320c9.74-19.41 16-40.81 16-64 0-23.51-6-44.4-16-64M400 368c19.48-34 32-64 32-112s-12-77.7-32-112'/>
    </svg>
)

const VolumeMediumSharp = createIcon(svgElement)

VolumeMediumSharp.displayName = 'VolumeMediumSharp'

export { IconProps } from './base/createIcon'

export default VolumeMediumSharp
