/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M256 48C141.13 48 48 141.13 48 256s93.13 208 208 208 208-93.13 208-208S370.87 48 256 48zm-9.17 241.14V344L146 248l100.83-96v54.86c96.5 0 119.17 69 119.17 137.14-27.85-35.57-52.48-54.86-119.17-54.86z'/>
    </svg>
)

const ArrowUndoCircleSharp = createIcon(svgElement)

ArrowUndoCircleSharp.displayName = 'ArrowUndoCircleSharp'

export { IconProps } from './base/createIcon'

export default ArrowUndoCircleSharp
