/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M48 256c0 114.87 93.13 208 208 208s208-93.13 208-208S370.87 48 256 48 48 141.13 48 256zm224-80.09L208.42 240H358v32H208.42L272 336.09l-22.7 22.54L147.46 256 249.3 153.37z'/>
    </svg>
)

const ArrowBackCircleSharp = createIcon(svgElement)

ArrowBackCircleSharp.displayName = 'ArrowBackCircleSharp'

export { IconProps } from './base/createIcon'

export default ArrowBackCircleSharp
