/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <circle cx='176' cy='416' r='16' fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32'/><circle cx='400' cy='416' r='16' fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M48 80L112 80 160 352 416 352'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M160 288h249.44a8 8 0 007.85-6.43l28.8-144a8 8 0 00-7.85-9.57H128'/>
    </svg>
)

const CartOutline = createIcon(svgElement)

CartOutline.displayName = 'CartOutline'

export { IconProps } from './base/createIcon'

export default CartOutline
