/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='44' d='M465 127L241 384 149 292'/><path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='44' d='M140 385L47 292'/><path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='44' d='M363 127L236 273'/>
    </svg>
)

const CheckmarkDoneSharp = createIcon(svgElement)

CheckmarkDoneSharp.displayName = 'CheckmarkDoneSharp'

export { IconProps } from './base/createIcon'

export default CheckmarkDoneSharp
