/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M132.43 162c-6.24-34-4.49-45.55-3.07-68.39L132.27 47a16 16 0 0115.94-15h215.57a16 16 0 0115.94 15l2.91 46.61c1.43 22.86 3.19 34.39-3.06 68.45-5.93 32.29-43.71 133.27-43.71 238.32V472a8 8 0 01-8 8H184.12a8 8 0 01-8-8v-71.63c.01-92.47-37.46-204.3-43.69-238.37z'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M135.21 96L376.79 96'/>
    </svg>
)

const PintOutline = createIcon(svgElement)

PintOutline.displayName = 'PintOutline'

export { IconProps } from './base/createIcon'

export default PintOutline
