/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M384 138a117.93 117.93 0 00-91.84 192h-72.32A118 118 0 10128 374h256a118 118 0 000-236zM54 256a74 74 0 1174 74 74.09 74.09 0 01-74-74zm330 74a74 74 0 1174-74 74.09 74.09 0 01-74 74z'/>
    </svg>
)

const RecordingSharp = createIcon(svgElement)

RecordingSharp.displayName = 'RecordingSharp'

export { IconProps } from './base/createIcon'

export default RecordingSharp
