/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='32' d='M400 352L464 288 400 224'/><path fill='none' strokeLinecap='square' strokeMiterlimit='10' strokeWidth='32' d='M448 288L48 288 48 160'/>
    </svg>
)

const ReturnDownForwardSharp = createIcon(svgElement)

ReturnDownForwardSharp.displayName = 'ReturnDownForwardSharp'

export { IconProps } from './base/createIcon'

export default ReturnDownForwardSharp
