/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M434.67 285.59v-29.8c0-98.73-80.24-178.79-179.2-178.79a179 179 0 00-140.14 67.36m-38.53 82v29.8C76.8 355 157 435 256 435a180.45 180.45 0 00140-66.92'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M32 256L76 212 122 256'/><path fill='none' strokeLinecap='round' strokeLinejoin='round' strokeWidth='32' d='M480 256L436 300 390 256'/>
    </svg>
)

const SyncOutline = createIcon(svgElement)

SyncOutline.displayName = 'SyncOutline'

export { IconProps } from './base/createIcon'

export default SyncOutline
