/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M256 48C141.13 48 48 141.13 48 256c0 114.69 93.32 208 208 208 114.86 0 208-93.14 208-208 0-114.69-93.31-208-208-208zm108 240H244a4 4 0 01-4-4V116a4 4 0 014-4h24a4 4 0 014 4v140h92a4 4 0 014 4v24a4 4 0 01-4 4z'/>
    </svg>
)

const TimeSharp = createIcon(svgElement)

TimeSharp.displayName = 'TimeSharp'

export { IconProps } from './base/createIcon'

export default TimeSharp
