/* eslint-disable */
// This file is automatically generated

import React from 'react'
import createIcon from './base/createIcon'

const svgElement = (
    <svg viewBox='0 0 512 512'>
        <path d='M237.65 176.1L144 176.1 144 335.9 237.65 335.9 368 440 368 72 237.65 176.1z'/>
    </svg>
)

const VolumeOffSharp = createIcon(svgElement)

VolumeOffSharp.displayName = 'VolumeOffSharp'

export { IconProps } from './base/createIcon'

export default VolumeOffSharp
