declare module '*.md'
declare module '*.scss'
declare module '*.png'
declare module '*.json'
declare module 'markdown-to-jsx'
declare module 'babel-standalone'
declare module 'highlight.js/lib/highlight'
declare module 'highlight.js/lib/languages/javascript'

declare module 'xl-vision/*'
declare module 'xl-vision'